/**
 * This module contains map of all errors codes to it text version
 * Docu on confluence
 */
const errors = {
  // 10xx - ROUTING
  NO_SCHEMA: 1000,
  REQUEST_VALIDATION_ERROR: 1001,
  // 11xx - SECURITY
  INVALID_CREDENTIALS: 1100,
  CANNOT_DESERIALIZE_USER: 1101,
  USER_IS_ALREADY_AUTHENTICATED: 1102,
  PERMISSION_MIDDLEWARE_CANNOT_FIND_PATH_IN_SETTINGS: 1103,
  NO_PERMISSION_TO_RESOURCE: 1104,
  CANNOT_LOGOUT_UNAUTHORIZED_USER: 1105,
  NOT_LOGGED: 1106,
  SERIALIZE_ERROR: 1107,
  ACCOUNT_IS_NOT_ACTIVE: 1108,
  // 12xx - DATABASE, MODELS
  MODEL_VALIDATION_NOT_PASS: 1200,
  MODEL_INSERT_INCORRECT_LENGTH: 1201,
  MODEL_UPDATE_INCORRECT_LENGTH: 1202,
  MODEL_FOUND_DOCUMENT_WITH_UNIQUE_FIELD: 1203,
  CANNOT_UPDATE_COLLECTED_POINT: 1204,
  CANNOT_UPDATE_TEAM_COLLECTED_POINTS: 1205,
  CANNOT_CREATE_USEREVENTS_DOCUMENT: 1206,
  CANNOT_UPDATE_USER_EVENTS: 1207,
  CANNOT_CREATE_TEAM: 1208,
  ADMINISTRATOR_CANT_COLLECT_POINTS: 1209,
  // 13xx - POINTS ERRORS
  POINT_NOT_EXIST: 1300,
  POINT_ALREADY_COLLECTED: 1301,
  // 14xx - KEYS/EVENTS ERRORS
  KEY_NOT_EXIST: 1400,
  KEY_OR_USER_NOT_EXIST: 1401,
  USER_ALREADY_PARTICIPLE_IN_THIS_EVENT: 1402,
  REQUIRE_TEAMNAME: 1403,
  THIS_USER_ID_DOESNT_BELONG_TO_YOU: 1404,
  // 15xx - 3rd part services
  MAIL_SERVICE_ERROR: 1500,
  // 16xx - Account activation / Password reset
  INVALID_ACTIVATION_KEY: 1600,
  CANNOT_UPDATE_USER_ACTIVATION: 1601,
  CANNOT_UPDATE_USER_RESET_PASSWORD_REQUEST: 1602,
  INVALID_RESET_KEY: 1603,
  PASSWORD_RESET_KEY_EXPIRED: 1604,
  CANNOT_UPDATE_USER_RESET_PASSWORD: 1605,
  // OTHER
  UNDEFINED_ERROR: 9900,
  RAW_ERROR: 9901,
};

module.exports = errors;
