paths:
  /events/:id:
    get:
      summary: 'Get event with :id (SECURED)'
      description: 'Special privilege required'
      tags:
        - Events
      responses:
        200:
          description: 'Event data'
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventName:
                    $ref: '#/components/props/eventName'
                  eventKey:
                    $ref: '#/components/props/eventKey'
                  eventDuration:
                    $ref: '#/components/props/eventDuration'
                  mapProperties:
                    $ref: '#/components/props/mapProperties'
                  eventRefreshTime:
                    $ref: '#/components/props/eventRefreshTime'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
    put:
      summary: 'Update event with :id (SECURED)'
      description: 'Special privilege required'
      tags:
        - Events
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                eventName:
                  $ref: '#/components/props/eventName'
                eventKey:
                  $ref: '#/components/props/eventKey'
                eventDuration:
                  $ref: '#/components/props/eventDuration'
                mapProperties:
                  $ref: '#/components/props/mapProperties'
                eventRefreshTime:
                  $ref: '#/components/props/eventRefreshTime'
      responses:
        200:
          description: 'Result of operation'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'