paths:
  /events:
    post:
      deprecated: true
      summary: 'Create event with (SECURED)'
      description: 'Special privilege required'
      tags:
        - Events
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                eventName:
                  $ref: '#/components/props/eventName'
                eventDuration:
                  $ref: '#/components/props/eventDuration'
                mapProperties:
                  $ref: '#/components/props/mapProperties'
                eventRefreshTime:
                  $ref: '#/components/props/eventRefreshTime'
      responses:
        200:
          description: 'Event data'
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventName:
                    $ref: '#/components/props/eventName'
                  eventDuration:
                    $ref: '#/components/props/eventDuration'
                  mapProperties:
                    $ref: '#/components/props/mapProperties'
                  eventRefreshTime:
                    $ref: '#/components/props/eventRefreshTime'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
  /events/:eventId:
    get:
      summary: 'Get event with :eventId (SECURED)'
      description: 'Special privilege required'
      tags:
        - Events
      responses:
        200:
          description: 'Event data'
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventName:
                    $ref: '#/components/props/eventName'
                  eventKey:
                    $ref: '#/components/props/eventKey'
                  eventDuration:
                    $ref: '#/components/props/eventDuration'
                  mapProperties:
                    $ref: '#/components/props/mapProperties'
                  eventRefreshTime:
                    $ref: '#/components/props/eventRefreshTime'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
    put:
      summary: 'Update event with :id (SECURED)'
      description: 'Special privilege required'
      tags:
        - Events
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                eventName:
                  $ref: '#/components/props/eventName'
                eventKey:
                  $ref: '#/components/props/eventKey'
                eventDuration:
                  $ref: '#/components/props/eventDuration'
                mapProperties:
                  $ref: '#/components/props/mapProperties'
                eventRefreshTime:
                  $ref: '#/components/props/eventRefreshTime'
      responses:
        200:
          description: 'Result of operation'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
  /events/check:
    post:
      summary: 'Allow user to check event, role, team that code'
      tags:
        - Events
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                eventKey:
                  $ref: '#/components/props/eventKey'
              required:
                - eventKey
      responses:
        200:
          description: 'Information about code'
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    $ref: '#/components/props/eventId'
                  role:
                    $ref: '#/components/props/role'
                  teamId:
                    $ref: '#/components/props/teamId'
        400:
          description: 'Validation error or none exist eventKey'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
  /events/join:
    post:
      summary: 'Allow user to join event (SECURED)'
      description: 'Special privilege required'
      tags:
        - Events
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  $ref: '#/components/props/id'
                eventKey:
                  $ref: '#/components/props/eventKey'
                teamName:
                  $ref: '#/components/props/teamName'
              required:
                - userId
                - eventKey
      responses:
        200:
          description: 'Successfully join to event'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
        400:
          description: 'Validation error or none exist eventKey'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'