paths:
  /api/v1/events/{eventId}/categories:
    get:
      summary: 'Get list of categories in event with eventId (SECURED)'
      description: 'Special privilege required'
      tags:
        - Categories
      parameters:
        - in: "path"
          name: eventId
          description: "Event id for looking categories"
          example: '300000000000000000000002'
          default: undefined
          required: true
      responses:
        200:
          description: 'Return list of categories'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    categoryId:
                      $ref: '#/components/props/id'
                    categoryName:
                      $ref: '#/components/props/categoryName'
                    pointValue:
                      $ref: '#/components/props/pointValue'
                    pointStrokeColor:
                      $ref: '#/components/props/pointStrokeColor'
                    pointFillColor:
                      $ref: '#/components/props/pointFillColor'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
        500:
          description: 'Server error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/500'
    post:
      summary: 'Add points category (SECURED)'
      description: 'Special privilege required'
      tags:
        - Categories
      parameters:
        - in: "path"
          name: eventId
          description: "Event id for looking categories"
          example: '300000000000000000000002'
          default: undefined
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryName:
                  $ref: '#/components/props/categoryName'
                pointValue:
                  $ref: '#/components/props/pointValue'
                pointStrokeColor:
                  $ref: '#/components/props/pointStrokeColor'
                pointFillColor:
                  $ref: '#/components/props/pointFillColor'
              required:
                - categoryName
                - pointValue
                - pointStrokeColor
                - pointFillColor
      responses:
        200:
          description: 'Successfully add category'
          content:
            application/json:
              schema:
                type: object
                properties:
                  categoryId:
                    $ref: '#/components/props/id'
                  categoryName:
                    $ref: '#/components/props/categoryName'
                  pointValue:
                    $ref: '#/components/props/pointValue'
                  pointStrokeColor:
                    $ref: '#/components/props/pointStrokeColor'
                  pointFillColor:
                    $ref: '#/components/props/pointFillColor'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
        500:
          description: 'Server error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/500'
