paths:
  /api/v1/events/:eventId/points:
    get:
      summary: 'Get list of points in event with eventId (SECURED)'
      description: 'Special privilege required'
      tags:
        - Points
      responses:
        200:
          description: 'Return list of points'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    pointId:
                      $ref: '#/components/props/id'
                    pointKey:
                      $ref: '#/components/props/pointKey'
                    pointName:
                      $ref: '#/components/props/pointName'
                    pointType:
                      $ref: '#/components/props/pointType'
                    pointCollectedDate:
                      $ref: '#/components/props/pointCollectedDate'
                    pointDuration:
                      $ref: '#/components/props/pointDuration'
                    pointPosition:
                      $ref: '#/components/props/pointPosition'
                    pointCategoryId:
                      $ref: '#/components/props/id'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
    post:
      summary: 'Add point (SECURED)'
      description: 'Special privilege required'
      tags:
        - Points
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pointId:
                  $ref: '#/components/props/id'
                pointName:
                  $ref: '#/components/props/pointName'
                pointKey:
                  $ref: '#/components/props/pointKey'
                pointType:
                  $ref: '#/components/props/pointType'
                pointDuration:
                  $ref: '#/components/props/pointDuration'
                pointPosition:
                  $ref: '#/components/props/pointPosition'
                pointCategoryId:
                  $ref: '#/components/props/id'
              required:
                - pointKey
                - pointName
                - pointType
                - pointPosition
                - pointCategoryId
      responses:
        200:
          description: 'Successfully add point'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
  /api/v1/events/:eventId/points/collect:
    post:
      summary: 'Collect point in event with eventId (SECURED)'
      description: 'Special privilege required'
      tags:
        - Points
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pointKey:
                  $ref: '#/components/props/pointKey'
              required:
                - pointKey
      responses:
        200:
          description: 'Result of operation'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
  /api/v1/events/:eventId/points/:pointId:
    put:
      summary: 'Update point with pointId from event with eventId (SECURED)'
      description: 'Special privilege required'
      tags:
        - Points
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pointKey:
                  $ref: '#/components/props/pointKey'
                pointName:
                  $ref: '#/components/props/pointName'
                pointType:
                  $ref: '#/components/props/pointType'
                pointDuration:
                  $ref: '#/components/props/pointDuration'
                pointPosition:
                  $ref: '#/components/props/pointPosition'
                pointCategory:
                  $ref: '#/components/props/id'
      responses:
        200:
          description: 'Result of operation'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
    delete:
      summary: 'Delete point with pointId from event with eventId (SECURED)'
      description: 'Special privilege required'
      tags:
        - Points
      responses:
        200:
          description: 'Result of operation'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
