components:
  props:
      email:
        description: 'User email. Used also as login'
        type: string
        format: email
        maxLength: 24
      password:
        description: 'User password'    
        type: string
        format: password
        minLength: 8
        maxLength: 24
      userEvents:
        description: 'List of events that user participle'
        type: array
      error:
        description: 'Error code name'
        type: number
        length: 4
      message:
        description: 'Error text name'
        type: string
      errorDetails:
        description: 'Validation details'
        type: object
      success:
        description: 'Field describe status of operation'
        type: boolean
        nullable: false
      roles:
        type: object
        properties:
          eventRole:
            description: 'Describe permissions in event scope'
            type: string
          teamRole:
            description: 'Describe permissions in team scope'
            type: string  
      eventName:
        description: 'Event name'
        type: string
      eventKey:
        description: 'Event access key'
        type: string    
      eventDuration:
        type: object
        properties:
          startDate:
            description: 'Time when event start'
            type: number
            nullable: true
          endDate:
            description: 'Time when event end'
            type: number
            nullable: true
      mapProperties:
        type: object
        properties:
          zoom:
            description: 'Default map zoom for user'
            type: number
          longitude:
            description: 'Default map longitude for user'
            type: number
          latitude:
            description: 'Default map latitude for user'
            type: number
      eventRefreshTime:
        description: 'Refresh time(in seconds) of map with points'
        type: number  