components:
  responses:
    400:
      message: 'Client error'
      type: object
      properties:
        error:
          $ref: '#/components/props/error'
        message:
          $ref: '#/components/props/message'
        errorDetails:
          $ref: '#/components/props/errorDetails'
      required:
        - error
        - message
    401:
      message: 'Security error'
      type: object
      properties:
        error:
          $ref: '#/components/props/error'
        message:
          $ref: '#/components/props/message'
        errorDetails:
          $ref: '#/components/props/errorDetails'
      required:
        - error
        - message
    500:
      message: 'Server error. Can have difference structure for uncached error'
      type: object
      properties:
        error:
          $ref: '#/components/props/error'
        message:
          $ref: '#/components/props/message'
        errorDetails:
          $ref: '#/components/props/errorDetails'
      required:
        - error
        - message
