components:
  responses:
    400:
      type: object
      properties:
        error:
          $ref: '#/components/props/error'
        message:
          $ref: '#/components/props/message'
        errorDetails:
          $ref: '#/components/props/errorDetails'
      required:
        - error
        - message
        - errorDetails
    401:
      type: object
      properties:
        error:
          $ref: '#/components/props/error'
        message:
          $ref: '#/components/props/message'
      required:
        - error
        - message  