paths:
  /auth/sign-up:
    post:
      summary: User registration endpoint
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 24
                  required: true
                  description: User nick/name
                email:
                  type: string
                  format: email
                  maxLength: 24                  
                  required: true
                  description: User email. Used also as login
                password:
                  type: string
                  format: password
                  minLength: 8
                  maxLength: 24
                  required: true
                  description: User password
      responses:
        200:
          description: 'User data'
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    nullable: false
                  email:
                    type: string
                    format: email
                    nullable: false
                  role:
                    description: "User permission lvl"
                    type: string
                    nullable: false  
        400:
          description: 'Validation error'
          content:
            application/json:
              schama:
                type: object
                properties:
                  error:
                    description: Error code name
                    type: number
                    length: 4
                  message:
                    description: Error text name
                    type: string
                  errorDetails:
                    description: Validation details
                    type: object
  /auth/sign-in:
    post:
      summary: Login endpoint
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object 
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 24
                  required: true
                  description: User nick/name
                password:
                  type: string
                  format: password
                  minLength: 8
                  maxLength: 24
                  required: true
                  description: User password
      responses:
        200:
          description: 'User data'
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    nullable: false
                  email:
                    type: string
                    format: email
                    nullable: false
                  role:
                    description: "User permission lvl"
                    type: string
                    nullable: false
        400:
          description: 'Validation error'
          content:
            application/json:
              schama:
                type: object
                properties:
                  error:
                    description: Error code name
                    type: number
                    length: 4
                  message:
                    description: Error text name
                    type: string
                  errorDetails:
                    description: Validation details
                    type: object    
  /auth/sign-out:
    post:
      summary: Logout endpoint
      tags:
        - Auth
      responses:
        200:
          description: 'Information if user logout'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    nullable: false
        400:
          description: 'Validation error'
          content:
            application/json:
              schama:
                type: object
                properties:
                  error:
                    description: Error code name
                    type: number
                    length: 4
                  message:
                    description: Error text name
                    type: string
                  errorDetails:
                    description: Validation details
                    type: object  
        401:
          description: 'Cannot logout unauthorized user'
          content:
            application/json:
              schama:
                type: object
                properties:
                  error:
                    description: Error code name
                    type: number
                    length: 4
                  message:
                    description: Error text name
                    type: string         