paths:
  /auth/sign-up:
    post:
      summary: 'User registration endpoint'
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/props/username'
                email:
                  $ref: '#/components/props/email'
                password:
                  $ref: '#/components/props/password'
              required:
                - username
                - email
                - password
      responses:
        200:
          description: 'User data'
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    $ref: '#/components/props/username'
                  email:
                    $ref: '#/components/props/email'
                  role:
                    $ref: '#/components/props/role'
                required:
                  - username
                  - email
                  - role    
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'   
  /auth/sign-in:
    post:
      summary: 'Login endpoint'
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object 
              properties:
                username:
                  $ref: '#/components/props/username'
                password:
                  $ref: '#/components/props/password'
              required:
                - username
                - password    
      responses:
        200:
          description: 'User data'
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    $ref: '#/components/props/username'
                  email:
                    $ref: '#/components/props/email'
                  role:
                    $ref: '#/components/props/role'
                required:
                  - username
                  - email
                  - role    
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401'
  /auth/sign-out:
    post:
      summary: Logout endpoint
      tags:
        - Auth
      responses:
        200:
          description: 'Information if user logout'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    $ref: '#/components/props/success'
                  required:
                    - success
        400:
          description: 'Validation error'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/400'
        401:
          description: 'No permissions'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401' 
